# Generated by Django 4.0.6 on 2022-11-14 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saloons', '0001_initial'),
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='saloon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saloons.saloon'),
        ),
        migrations.AddField(
            model_name='barber',
            name='schedule',
            field=models.ManyToManyField(blank=True, to='barbers.schedule'),
        ),
        migrations.AddField(
            model_name='barber',
            name='service',
            field=models.ManyToManyField(blank=True, to='barbers.service'),
        ),
    ]
