# Generated by Django 4.0.6 on 2022-07-11 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0002_remove_saloon_barbers'),
        ('barbers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='saloon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saloons.saloon'),
        ),
    ]
