# Generated by Django 4.0.6 on 2022-07-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0004_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='barber',
            name='schedule',
            field=models.ManyToManyField(blank=True, to='barbers.schedule'),
        ),
        migrations.AddField(
            model_name='barber',
            name='service',
            field=models.ManyToManyField(blank=True, to='barbers.service'),
        ),
    ]
