# Generated by Django 4.0.6 on 2022-07-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0005_service_barber_schedule_barber_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.DateTimeField(blank=True),
        ),
    ]
