# Generated by Django 4.0.6 on 2022-07-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0006_schedule_is_available_alter_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
