# Generated by Django 4.0.6 on 2022-07-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0007_service_description_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
