# Generated by Django 4.0.6 on 2022-11-14 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saloons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barbers', '0003_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloon',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.admin'),
        ),
        migrations.AddField(
            model_name='review',
            name='saloon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saloons.saloon'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbers.barber'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='saloon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saloons.saloon'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbers.service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
