# Generated by Django 4.0.6 on 2022-11-14 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('saloons', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saloon',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.admin'),
        ),
    ]
