# Generated by Django 4.0.6 on 2023-02-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0003_alter_saloon_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloon',
            name='layout_image',
            field=models.ImageField(blank=True, upload_to='header'),
        ),
        migrations.AddField(
            model_name='saloon',
            name='layout_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
