# Generated by Django 4.0.6 on 2023-02-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0003_alter_saloon_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='header')),
                ('text', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='saloon',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='header'),
        ),
        migrations.AddField(
            model_name='saloon',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
   
    ]
