# Generated by Django 4.0.6 on 2023-02-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0004_saloon_layout_image_saloon_layout_text_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloon',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='header'),
        ),
        migrations.AddField(
            model_name='saloon',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
