# Generated by Django 4.0.6 on 2023-02-05 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0004_layout_saloon_favicon_saloon_title_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloon',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saloons.layout'),
        ),
      
    ]
