# Generated by Django 4.0.6 on 2022-07-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0006_appointment_delete_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
