# Generated by Django 4.0.6 on 2022-08-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0008_appointment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='schedule',
            field=models.DateTimeField(blank=True),
        ),
    ]
