# Generated by Django 4.0.6 on 2022-08-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0009_alter_appointment_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saloon',
            old_name='adress',
            new_name='address',
        ),
    ]
