# Generated by Django 4.0.6 on 2022-09-03 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_admin'),
        ('saloons', '0010_rename_adress_saloon_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloon',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.admin'),
        ),
    ]
