# Generated by Django 4.0.6 on 2022-09-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0011_saloon_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
