# Generated by Django 4.0.6 on 2022-08-22 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0009_alter_appointment_schedule'),
        ('users', '0003_rename_first_name_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saloon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saloons.saloon'),
        ),
    ]
