# Generated by Django 4.0.6 on 2022-08-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_saloon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_spent',
            field=models.FloatField(null=True),
        ),
    ]
